from tools import solarmag
import numpy as np, pylab as pl, pyfits as py
import cPickle
from makemodel import *
from astLib import astCalc
from imageSim import SBObjects
from itertools import product

cat = np.load('/data/ljo31/public_html/Lens/phys_models/synthetic_both/n=6/ML_CATALOGUE')
Mstar = np.array([cat[i][0] for i in range(len(cat))])
re_norm = np.array([cat[i][2] for i in range(len(cat))])
re_nugg = np.array([cat[i][3] for i in range(len(cat))])
rhalo = np.array([cat[i][4] for i in range(len(cat))])
Mhalo = np.array([cat[i][5] for i in range(len(cat))])
vd_norm = np.array([cat[i][6] for i in range(len(cat))])
vd_nugg = np.array([cat[i][7] for i in range(len(cat))])
mdm_nugg = np.array([cat[i][8] for i in range(len(cat))])
mdm_norm = np.array([cat[i][9] for i in range(len(cat))])
sigma_dm_nugg = np.array([cat[i][10]**0.5 for i in range(len(cat))])
sigma_star_nugg = np.array([cat[i][11]**0.5 for i in range(len(cat))])
sigma_dm_norm = np.array([cat[i][12]**0.5 for i in range(len(cat))])
sigma_star_norm = np.array([cat[i][13]**0.5 for i in range(len(cat))])


mstar = 10**Mstar


Mtot = np.log10(10**Mstar + 10**Mhalo)
logrnugg = np.log10(re_nugg)
logrnorm = np.log10(re_norm)

mstar = np.log10(mstar/2.)
mdm_norm = np.log10(mdm_norm)
mdm_nugg = np.log10(mdm_nugg)
mtot_norm = np.log10(10**mstar + 10**mdm_norm)
mtot_nugg = np.log10(10**mstar + 10**mdm_nugg)

pl.subplot(131)
pl.plot(mstar,np.log10(re_norm),label='normals')
pl.plot(mstar,np.log10(re_nugg),label='nuggets')
pl.xlabel('$\log M_{\star}$')
pl.ylabel('$\log r_e$')
pl.subplot(132)
pl.plot(mtot_norm,np.log10(re_norm),label='normals')
pl.plot(mtot_nugg,np.log10(re_nugg),label='nuggets')
pl.xlabel('$\log M_{tot}$')
pl.ylabel('$\log r_e$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(131)
pl.legend(loc='lower right',fontsize=15)
pl.subplot(133)
pl.plot(mtot_norm-mstar,np.log10(re_norm),label='normals')
pl.plot(mtot_nugg-mstar,np.log10(re_nugg),label='nuggets')
pl.xlabel('$\log (M_{tot}/M_{\star})$')
pl.ylabel('$\log r_e$')
pl.legend(loc='lower right',fontsize=15)


pl.figure()
pl.subplot(131)
pl.plot(mstar,np.log10(sigma_star_norm),label='normals')
pl.plot(mstar,np.log10(sigma_star_nugg),label='nuggets')
pl.xlabel('$\log M_{\star}$')
pl.ylabel('$\log \sigma_{\star}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(132)
pl.plot(mstar,np.log10(sigma_dm_norm),label='normals')
pl.plot(mstar,np.log10(sigma_dm_nugg),label='nuggets')
pl.xlabel('$\log M_{\star}$')
pl.ylabel('$\log \sigma_{dm}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(133)
pl.plot(mstar,np.log10(vd_norm),label='normals')
pl.plot(mstar,np.log10(vd_nugg),label='nuggets')
pl.xlabel('$\log M_{\star}$')
pl.ylabel('$\log \sigma_{tot}$')
pl.legend(loc='lower right',fontsize=15)

pl.figure()
pl.subplot(131)
pl.plot(mtot_norm,np.log10(sigma_star_norm),label='normals')
pl.plot(mtot_nugg,np.log10(sigma_star_nugg),label='nuggets')
pl.xlabel('$\log M_{tot}$')
pl.ylabel('$\log \sigma_{\star}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(132)
pl.plot(mtot_norm,np.log10(sigma_dm_norm),label='normals')
pl.plot(mtot_nugg,np.log10(sigma_dm_nugg),label='nuggets')
pl.xlabel('$\log M_{tot}$')
pl.ylabel('$\log \sigma_{dm}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(133)
pl.plot(mtot_norm,np.log10(vd_norm),label='normals')
pl.plot(mtot_nugg,np.log10(vd_nugg),label='nuggets')
pl.xlabel('$\log M_{tot}$')
pl.ylabel('$\log \sigma_{tot}$')
pl.legend(loc='lower right',fontsize=15)

pl.figure()
pl.subplot(131)
pl.plot(mtot_norm-mstar,np.log10(sigma_star_norm),label='normals')
pl.plot(mtot_nugg-mstar,np.log10(sigma_star_nugg),label='nuggets')
pl.xlabel('$\log (M_{tot}/M_{\star})$')
pl.ylabel('$\log \sigma_{\star}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(132)
pl.plot(mtot_norm-mstar,np.log10(sigma_dm_norm),label='normals')
pl.plot(mtot_nugg-mstar,np.log10(sigma_dm_nugg),label='nuggets')
pl.xlabel('$\log (M_{tot}/M_{\star})$')
pl.ylabel('$\log \sigma_{dm}$')
pl.legend(loc='lower right',fontsize=15)
pl.subplot(133)
pl.plot(mtot_norm-mstar,np.log10(vd_norm),label='normals')
pl.plot(mtot_nugg-mstar,np.log10(vd_nugg),label='nuggets')
pl.xlabel('$\log (M_{tot}/M_{\star})$')
pl.ylabel('$\log \sigma_{tot}$')
pl.legend(loc='lower right',fontsize=15)

